### ISSUE TITLE
With jest get error:  Cannot find module 'sinon' from 'import-mock.js'

### ISSUE THREAD

**Issue by samrae7** [EmandM/ts-mock-imports#7]
Using this with jest, I get the following error:

```
  ● Test suite failed to run

    Cannot find module 'sinon' from 'import-mock.js'

    However, Jest was able to find:
    	'./import-mock.d.ts'
    	'./import-mock.js'
    	'./import-mock.js.map'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js', 'json', 'jsx', 'node', 'd.ts', 'js.map'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:230:17)
      at Object.<anonymous> (node_modules/ts-mock-imports/src/import-mock.ts:1:1)
```

(NB: Adding "d.ts" and "js.map" to `modulefileextensions-array-string` help)

**Comment by EmandM** [comment]
Sinon is listed as a peer dependency for this project. That means when you install ts-mock-imports, you need to also install sinon to your local project.
